### ISSUE TITLE
Consider adding bluez5.msbc-support=true in /etc/pipewire/media-session.d/bluez-monitor.conf

### ISSUE THREAD

**Issue by mcarans** [pipewire-debian/pipewire-debian#12]
My headset worked with your PPA. Thanks so much for this. The only thing I needed to change was to put bluez5.msbc-support=true in /etc/pipewire/media-session.d/bluez-monitor.conf to enable SBC as the quality was poor with the default CVSD when using the microphone. 

Maybe you could consider making this the default? I'd be surprised if today the warning about "mSBC is not expected to work on all headset + adapter combinations" is still a common problem and anyway, for those rare cases, people could edit the file to set it to false.

**Comment by pipewire-debian** [comment]
Thanks @mcarans  for your feedback.
> Maybe you could consider making this the default?

No, The main goal of this PPA 
1. To provide the latest release of PipeWire to `debian/ubuntu` users without modifying anything as the version is very old on their official repository.
2. To help its developers to make the PipeWire a bugfree product. As the Majority of Linux users targets `ubuntu/debian` based distros, If they can test PipeWire and report bugs or feature request to upstream you are unknowingly contribute to the project.



 In the name of stabilization `ubuntu/debian` packagers are not considering to provide it to their users to test. PipeWire evolves a lot since before. If something breaks on PipeWire ( for heavy devlopment 8~10 commit per day) you can file an issue on [upstream](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues) until it won't be fixed  you may consider to switch to PulseAudio quickly (just you need to disable PipeWire related services and enable PA related service thats it). 
 
 So can you please create the same issue  on [upstream](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues) ?

**Comment by mcarans** [comment]
Thanks @pipewire-debian. I have created it here: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1201

**Comment by souravdas142** [comment]
great. pipewire 0.3.28 will be released within 2 days... stay tuned.

**Comment by souravdas142** [comment]
hii 0.3.28 is released.

**Comment by mcarans** [comment]
I will close this here since the issue is raised upstream

**Comment by souravdas142** [comment]
**Some updates -**

@mcarans  were you want https://gitlab.freedesktop.org/pipewire/pipewire/-/merge_requests/779 ? just merged.

**Comment by mcarans** [comment]
@souravdas142 That looks like good news. Thx!

**Comment by mcarans** [comment]
I tried removing my config change and using the fresh one:
`sudo cp -vRa /usr/share/pipewire /etc/`

It now offers msbc by default.

**Comment by souravdas142** [comment]
@mcarans  Thats great  :slightly_smiling_face: . should this now be closed ?

**Comment by mcarans** [comment]
@souravdas142 Sure I think it can be. I will do so.
