### ISSUE TITLE
Remove depreciated instructions

### ISSUE THREAD

**Issue by jacksongoode** [pipewire-debian/pipewire-debian#18]
Not sure if they are reliable or needed for the users that would be interested in them.

**Comment by jacksongoode** [comment]
Also I would not use the [svg](https://raw.githubusercontent.com/wiki/pipewire-debian/pipewire-debian/images/icons/deprecated.svg) you are using. Stick with Markdown formatting as it is more clear and compatible.

**Comment by souravdas142** [comment]
Actually I think this `deprecated` Instructions are also important here. for example [README.md#L238](https://github.com/pipewire-debian/pipewire-debian/blame/bd591338ae56827459bc428353391a58b540f658/README.md#L238) The **Debian Wiki** for `PipeWire` is deprecated for this PPA right? But People still goes to the `Debian Wiki` for the installation instruction, Some blogger also misguide their readers in that way. **So here, I explicitly tell, that the `Debian Wiki` is deprecated for this PPA.** Don't know how much people read the `PPA description` while adding them to their system, But I also mentioned there this Wiki/README as a  reference for the installation instructions, And not the blogger one that is totally misguided. for reference see : https://ubuntuhandbook.org/index.php/2021/05/install-latest-pipewire-ppa-ubuntu-20-04 this is the one, there are many available like that. 

**[This Github hosted Repo : #L95-L104](https://github.com/pipewire-debian/pipewire-debian/blame/bd591338ae56827459bc428353391a58b540f658/README.md#L95-L104) -** This is also deprecated, because of somehow I feel this is redundant of LP PPA,  The purpose of creating this, because of I was thought that time, Apart from ubuntu or its derivative can not use LP PPA. But I was wrong, Now I am realising All most all packages from LP PPA can be installed on  debian or its derivative.
But Somehow I still feel It can be used some debugging purpose and also I have referenced this **Github hosted PPA** from the wiki pages mentioning `how to create like that one`, I think it's still needed placed on README.

---

> Also I would not use the svg you are using. Stick with Markdown formatting as it is more clear and compatible.

Yeah, I also want to stick with `markdown` formatting, but emojis are not rendering on `github pages`. As they are not rendering, the `markdown` format text are showing like `:hammer_and_wrench:` which make a reader out of focused right ? ok see this [waybackMachine](https://web.archive.org/web/20210513114633/https://pipewire-debian.github.io/pipewire-debian) saved github page for that, So were emojis rendering on this github page? Thats why I converted them to `svg`.  

Now you can questioned, "Whats wrong about other 'README.md (on development branch) or Home.md (on wiki) thats not involved in `github page`? Why I am not followed the putting `emojis` instead of `svg` there?"

Well the simple answer is its reduce maintenance a lot. whatever changes I made for one, I use to copy that file to the `development` branch or `wiki`.

---

**Conclusion -**          

I don't want to use `svg` becasue on some browser like `firefox` shows this `svg` not very well, see this below screenshot.     

![image](https://user-images.githubusercontent.com/24272753/121108396-4f05ec00-c827-11eb-91a2-c29eceeef57d.png)

There is no issue in other browser like `brave` or `chrome` or on any `chromium` based engine. But I think without `svg` there is no other way to show those `emojis` properly on `github page` as well as on `markdown`. 

Do you have any other Idea  for displaying `emojis` in both case? **Thank You**

**Comment by souravdas142** [comment]
Hii @jacksongoode , Any suggestions?

**Comment by jacksongoode** [comment]
Those are good points, I understand you wanting the Github pages to have proper icons. In this case I would make sure these svg's are standardized and unified, maybe [Twemoji](https://twemoji.twitter.com/)? The svgs next to the title are fine. I still would suggest that the "depreciated" svg be removed, as I haven't had it render correctly on any browser I've used (Firefox, Chrome).

**Comment by souravdas142** [comment]
> In this case I would make sure these svg's are standardized and unified, maybe Twemoji?

But I don't know how to use it. Can you please leave a comment with a `twemoji` emoji as an example?

>  I still would suggest that the "depreciated" svg be removed, as I haven't had it render correctly on any browser I've used (Firefox, Chrome).

Previously last portion of "DEPRECATED" text svg was cut out due to wrong dimension, After refactoring the dimension d567e0feb09533f9ab522ea32d7ac2952398109c, that issue was resolved. I'have checked with phone browser as well as desktop browsers (All browsers that are available), "DEPRECATED" text svg are now rendering properly. Can you please check it again? Please let me know if still have problems with rendering.           

 **"DEPRECATED" svg :** I'm using `svg` over simple formatted text, because I've to make the font color `red` and as far as I know there is no way to make it. Do you have any alternative idea?

**Comment by avoidik** [comment]
that's how svg looks like

![image](https://user-images.githubusercontent.com/6435932/124396466-68109880-dd12-11eb-9e8f-1fd033babb0f.png)

**Comment by souravdas142** [comment]
@avoidik  Hmm... strange, I've not this issue, And trying hard to reproduce this but can't. Can you share the browser name with version and from which distro are you browsing from ? Does the same svg in wiki section have the same rendering issue ?            


This "Deprecated" message I can't remove because the `master` holds a repo from which pipewire and other tools can also be installed, But seems there are outdated packages, One shouldn't use from there. and this should be informed to others. For more read first 2 paragraph from https://github.com/pipewire-debian/pipewire-debian/issues/18#issuecomment-856373143

**Comment by avoidik** [comment]
I think this is due to hidpi scaling, I have scale ratio of 2.

**Comment by souravdas142** [comment]
> I think this is due to hidpi scaling, I have scale ratio of 2.

Then any Idea how to solve this and make it visually work universally ?

**Comment by souravdas142** [comment]
@avoidik  

 > I think this is due to hidpi scaling, I have scale ratio of 2.

Then any Idea how to solve this and make it visually work universally ?

**Comment by avoidik** [comment]
By using plain text

**Comment by souravdas142** [comment]
@avoidik  LOL, I will change it. BTW the same svg in wiki section, have the same rendering issue ?

**Comment by souravdas142** [comment]
Hii @avoidik  and @jacksongoode   This is last time I pushed a commit correcting "deprecated" svg. This time I padded 2px all around of the text, Can you check it whether things are good or not?

If this is not fixed I'll drop svg and will be using plain text only. Thanks.
