### ISSUE TITLE
removing pipewire killed my os

### ISSUE THREAD

**Issue by bwanaaa** [pipewire-debian/pipewire-debian#19]
**If you Completed all troubleshoot options, check below**     
- [ x]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [x ]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Describe the bug**
properly installed pipe wire.
then decided to remove it with
`sudo apt purge gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,media-session,bin,locales,tests}}
`
now system does not boot

I tried to repair by booting to recovery environment, enabling networking and typing

`sudo apt-get install --fix-broken`

did not work

`sudo apt install gstreamer1.0-pipewire libpipewire-0.3-{0,dev,modules} libspa-0.2-{bluetooth,dev,jack,modules} pipewire{,-{audio-client-libraries,pulse,media-session,bin,locales,tests}}`

did not work

I tried  following these instructions

`https://ostechnix.com/how-to-fix-broken-ubuntu-os-without-reinstalling-it/`

did not work

I dropped to recovery environment and updated grub

did not work.

**Expected behavior**
please help?

**Desktop (please complete the following information):**
ubuntu 21.04

**Journal log and status of related services**

**Comment by bwanaaa** [comment]
figured it out

sudo apt -y install ubuntu-desktop

I guess somehow gnome got connfused

**Comment by souravdas142** [comment]
Any feedback why did you remove? any suggestions ? @bwanaaa  also see https://github.com/pipewire-debian/pipewire-debian/issues/19#issuecomment-861206344

**Comment by souravdas142** [comment]
@bwanaaa  Actually the issue was, PipeWire 0.3.24 shipped with ubuntu 21.04 by default, Therefore no way to completely remove it without breaking other core package because Other core packages may have dependencies on PipeWire. And you checked all boxes blindly without actually checking the links before creating the issue here. On the [Troubleshooting](https://github.com/pipewire-debian/pipewire-debian/wiki/Troubleshooting) page, There I clearly mentioned how to uninstall/downgrade PipeWire on the above situation.  **PLEASE INSTALL PIPEWIRE STOCK  VERSION, LIKE AS IT WAS"**. otherwise this issue impact on the PPA. I'm giving pastebin link here, that proves the whole comment. [hirsute_ubuntu20.04_PipeWire_install_log.txt](https://pastebin.com/zZ4Rx2im)

**Also duplicate of #14**
