### ISSUE TITLE
When will 0.35v drop?

### ISSUE THREAD

**Issue by NicoForce** [pipewire-debian/pipewire-debian#31]
First, Thanks for the god work Sourav.

Just asking, as 0.35v release is ready, when will it be ready in the ppa?

**Comment by souravdas142** [comment]
It will be available within 30 mins. 

Sorry man I have no time... In future may be I can't be update on the release day. I will release definitely but some delay may occur.

**Comment by NicoForce** [comment]
Don't worry about it, thanks for your work. If there is anything I can help with automating, I'll be glad to!

**Comment by souravdas142** [comment]
No, CI/CD may not be done here... I think some manual intervention is needed. Although its bad idea to update something on the same release date because of some bugs may interrupt the building or running process and these all are time consuming. The package PipeWire for arch linux is designed such a way that a very very little manual intervention is needed. In that case it can be automated. but not it.
