### ISSUE TITLE
libcamera0 version 0.r3171.43d098ce-1~ubuntu20.04 appears to break webcam

### ISSUE THREAD

**Issue by Slater91** [pipewire-debian/pipewire-debian#37]
**If you Completed all troubleshoot options, check below**     
- [x]  Did you Follow all installation instructions carefully from [here](../wiki/#1-ppa-configuration)?
- [x]  Did you check All troubleshoot options from [here](../wiki/Troubleshooting)?

**Describe the bug**
After updating to libcamera0 libcamera0 0.r3171.43d098ce-1~ubuntu20.04, the webcam is not detected any more by the system. This also makes commands such as lsusb hang forever. As you can see in the log at the end of the report, the webcam is actually detected by the kernel, but as soon as I log in, it is disconnected, which seems to indicate that there is a problem with libcamera0. The problem was also not there before I updated to the latest version.

As previous versions of packages from PPAs are deleted, it is also impossible for me to test out the previous version to rule out other possible issues. I have already tried going through the packages I've installed in the past week, as well as booting with a previous kernel version, but to no avail. If you could provide me with version 0.r3072.c8c1d07c-1~ubuntu20.04, it would be much easier.

On top of this, it seems like this breaks the whole USB subsystem, as the computer won't shut down or reboot. It hangs showing the following message: "A stop job is running for LSB: this services [sic] starts and stops the USB Arbitrator."

**To Reproduce**
Install libcamera0 version 0.r3171.43d098ce-1~ubuntu20.04.

**Expected behavior**
The webcam keeps on working as usual.

**Desktop (please complete the following information):**
 - Distro: KDE neon, based on Ubuntu 20.04
 - Desktop Environment: KDE Plasma
 - Version: 20.04

**Journal log and status of related services**
[    5.262403] usb 4-2: Found UVC 1.00 device HP HD Camera (04f2:b5ee)
[    5.281758] input: HP HD Camera: HP HD Camera as /devices/pci0000:00/0000:00:08.1/0000:04:00.4/usb4/4-2/4-2:1.0/input/input28
[    5.281900] usbcore: registered new interface driver uvcvideo
[    6.120674] usbcore: registered new interface driver btusb
[   15.611058] usb 4-2: USB disconnect, device number 3
[   15.651510] usb usb4-port2: couldn't allocate usb_device

**Comment by souravdas142** [comment]
Sorry for the delay.

> As previous versions of packages from PPAs are deleted, it is also impossible for me to test out the previous version to rule out other possible issues

Older packages can always  accessible from [https://launchpad.net/~pipewire-debian/+archive...](https://launchpad.net/~pipewire-debian/+archive/ubuntu/pipewire-upstream/+packages?field.name_filter=&field.status_filter=&field.series_filter=)  If you want to check with older version you can and report here. 

`libcamera` issue tracker  : https://bugs.libcamera.org/

`PipeWire` issue tracker : https://gitlab.freedesktop.org/pipewire/pipewire/-/issues

Also I couldn't see a big change since 3171 : https://git.linuxtv.org/libcamera.git/log/  So I want you to create an issue regarding  the same on `libcamera`  also.

**Comment by Slater91** [comment]
No worries at all, thank you for your reply and for your help!
I swear I have searched for the better part of an hour for the archives, and yet I could not find anything. At this point I must seriously reconsider my search engine skills.
Jokes aside, I have tried installing pipewire 0.3.38, as 0.3.39 is incompatible with the previous version of libcamera0, and it works perfectly, so there is indeed a bug somewhere. I will open reports on PipeWire's and Libcamera's trackers as well.

**Comment by souravdas142** [comment]
:sweat_smile: 
 > I will open reports on PipeWire's and Libcamera's trackers as well.

before opening a report to those repos, please try previous version of libcamera0 If something is wrong with this PPA package devs are get offended for wasting their times.                                 
      **You** are saying the version 3072 doesn't have any problem. We can do a `git bisect` on those nearely 100 commits and can find a commit from where the problem occurs.

**Comment by Slater91** [comment]
Sorry, I think there is a misunderstanding as maybe I wasn't clear enough. **I have installed** version 3072 along with PipeWire 0.3.38 and I confirm it works 100%. I couldn't try version 3072 with PipeWire 0.3.39 because the latter is packaged with a hard dependency on version 3171.

**Comment by souravdas142** [comment]
> I couldn't try version 3072 with PipeWire 0.3.39 because the latter is packaged with a hard dependency on version 3171.

exactly what i was going to write. I didn't notice its hard dependent on version 3171. Ok then you can report to the other repos. BTW, 

> To Reproduce
Install libcamera0 version 0.r3171.43d098ce-1~ubuntu20.04.

should i need to reboot or the moment after installing its happening ?

**Comment by Slater91** [comment]
> should i need to reboot or the moment after installing its happening ?

I reconstructed through the logs that I didn't reboot, but the camera stopped working anyway: at first it worked, but after a minute or so it started doing weird things and broke. I tried opening and closing the application, but at that point it said it couldn't find a camera.

**Comment by souravdas142** [comment]
**The problem is not reproducing here.. I've tried on 2 device**

After 2 hrs still I can't reproduce the problem. The camera app I have tested : Cheese, Webcamoid, Kamoso

First I installed pipewire and all its relevant package along with libcamera0 version 3171, 

The cheese immediately stops showing images at 640p but when I swithched to 1280p its normally working (At this point, I've not enable any service related to pipewire, thats mean server is pulseaudio), Webcamoid, Kamoso working nomarlly without any issue.

After enabling all pipewire related service there still have no issue except cheese, and the issue was same. **There was no sign of breaking the whole usb substem or the single one.** 

I think 2 hrs is enough to show any problem if its really have problem ?? or For you do you need to wait more than 2 hrs to reproduce the same ? 

Can you please install libcamera version 3171 with pipewire version 0.3.38-2 . The dependency of pipewire on libcamera is (>= 3070), So you can install libcamera 3171 without upgrading pipewire. Please try and report me back.

**Comment by Slater91** [comment]
Have you tried with a laptop with the same camera? The hardware ID is provided in my first message: 04f2:b5ee.
I have tried updating to version 3171 and it does work, albeit patchily: sometimes it does show pictures, sometimes it doesn't. dmesg doesn't show any errors or weird behaviour. I also had to reset the USB HCI/XHCI stack in order for the webcam to work. 
The problem does seem to be elsewhere then, probably in PipeWire itself somehow.

**Comment by souravdas142** [comment]
> Have you tried with a laptop with the same camera?

No, But the vendor ID is same (Mine is : 04f2:b509) for both.. BTW may be the problem specific to only that particular hardware. And this hardware is not available to me. 

Ok you already filed a bug report : https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1799 , May be devs can tell you to provide more information. If they need any help I will be happily committed.

One thing I think you forget to mention, The commit hash from where libcamera version 3171 has been built and that is 43d098ce5f2733dbde249d33d3b418cbeadfaaa5 . Please mention that. And one thing : the pipewire is built from  :  f6b1d65e35fd653d11b3c0afe0e818f9eaff8e57

**Comment by souravdas142** [comment]
Ok.. meanwhile `PipeWire 0.3.40` released and package released under [Testing Launchpad Repo](https://launchpad.net/~pipewire-debian/+archive/ubuntu/bionic-qt5125). I also bump the `libcamera` version to 3223. Can you please upgrade libcamera to version 3223 with pipewire 0.3.38 and check whether your problem is solved or not ? Then upgrade pipewire to 0.3.40, check again . The testing repo holds pipewire and libcamera only for ubuntu 20.04 for now.

Testing repo can be added : 
```bash
 sudo add-apt-repository ppa:pipewire-debian/bionic-qt5125 && sudo apt-get update
```

I'll not release `PipeWire` to main repo until some bugs related to 0.3.40 gets fixed

**Comment by Slater91** [comment]
Sure, I will do as soon as I can, hopefully tonight. Thanks for the help, it's really appreciated.

**Comment by Slater91** [comment]
I've just tested it. I can confirm that the webcam is still broken with the new build from the testing repo. What's worse is that now I can't get it to work with PipeWire 0.3.38 with any kernel, either, so I am really at a loss of what to do and what component is at fault here...

**Comment by souravdas142** [comment]
Please report to the `libcamra` issue tracker also, See : https://github.com/pipewire-debian/pipewire-debian/issues/37#issuecomment-964916290

**EDIT :** Can you check Installing all other libcamera subpackages whether issue is fixed or not ?

**Comment by Slater91** [comment]
I've done a lot more research and experimentation to try to nail down the issue better. It looks like, despite my efforts in finding the cause of the issue, I was wrong the entire time and that other issues were at play. At one point I even started suspecting hardware fault! It turns out that it was a bug with TLP (https://github.com/linrunner/TLP/issues/587) all the time and that simply disabling the service was not enough, I had to remove the package for the system to start behaving normally again. The update to the newer libcamera0 package appeared to trigger the issue, but at this point I can safely rule out that this was the case - the update simply showed a symptom of an underlying issue.
Thank you for your help and support in this, I really appreciate it.
