### ISSUE TITLE
0.3.40 release

### ISSUE THREAD

**Issue by v1993** [pipewire-debian/pipewire-debian#38]
First of all, thanks a lot for your work on this repo!

Is there any estimate when will 0.3.40 will drop? It have been over a week.

**Comment by souravdas142** [comment]
Sorry for that. Actually there are lots of issue  people facing with 0.3.40 and reporting to upstream (at a rate of 4 per day) that are actually not solving by devs even not addressing them. If something broken I've not lot of time to find the bug checking out before a bad commit that leads to the bug and re-upload every time. There is also #37  reported and not solved. Also there is a bug in wireplumber that leads lot of problem. So I am thinking to drop 0.3.40 and will upload 0.3.41 which is expected comming next week by Thursday. 

If you are using ubuntu 20.04 upgrade pipewire to 0.3.40,  The testing repo holds pipewire and libcamera only for ubuntu 20.04 for now.

Testing repo can be added : 
```bash
 sudo add-apt-repository ppa:pipewire-debian/bionic-qt5125 && sudo apt-get update
```

I'll not release `PipeWire` to main repo until some bugs related to 0.3.40 gets fixed

**Comment by NicoForce** [comment]
I was wondering about 0.3.40 but you left a clear message.

Thanks for your efforts!

**Comment by v1993** [comment]
Alright, thanks a lot for explaining! I'm facing some bugs that were fixed in 0.3.40, so I was wondering what's the reason for lack of updates. Once again, thanks for taking your time to work on this!

**Comment by nemoforum** [comment]
@souravdas142 
Thank you for all your effort!
0.3.40 fixes https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/640 at least.

**Comment by stuaxo** [comment]
Hi,

Thanks for the work on packaging this.

I was here as it looks like 0.3.40 looks like it may fix the issue where changing devices in pavucontrol or microsoft teams switches the device to "Unknown device" and there is no sound output.

https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1821

I'd like to try 0.3.40 since sound is pretty much useless on my computer because of this bug (I realised this was a possible outcome when switching from pulseaudio !)

**Comment by stuaxo** [comment]
Scrolling up - I checked out #37, that has been closed and seems like not a bug in pipewire.

**Comment by souravdas142** [comment]
Wait for tonight. I will update repo with master - PipeWire, WirePlumber, media-session, libcamera,  blueman.

**Comment by stuaxo** [comment]
Thanks for your work, I now have working pavucontrol, I haven't tried the other bits yet - but this is working a lot more than before.

**Comment by souravdas142** [comment]
**If possible install [`WirePlumber`](https://launchpad.net/~pipewire-debian/+archive/ubuntu/wireplumber-upstream) instead of [`pipewire-media-session`](https://gitlab.freedesktop.org/pipewire/media-session) as recommended by upstream.**

You can install it by adding another PPA : ```sudo add-apt-repository ppa:pipewire-debian/wireplumber-upstream``` 
you can see more installation instruction in [README.md](https://github.com/pipewire-debian/pipewire-debian/blob/master/README.md)

I have already started advertise in installation changelog. People are seen to report at upstream regarding on bugs like :       

[Moving sink-input to different sink causes it to jump to an unknown sink](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1870)
[pipewire-pulse 3.40. Broken tcp input](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1863)
[Switching audio device on pavudevice switches to non existent device "Unknown output".](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1821)
[Switching to a different sink stops playback](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1795)


**You can see the deprecation declaration in changelong from pipewire 0.3.39** And I don't know `pipewire-media-session` is still in development.

> [PipeWire 0.3.39 (2021-10-21)](https://gitlab.freedesktop.org/pipewire/pipewire/-/releases)
> This is a bugfix release that is API and ABI compatible with previous 0.3.x releases.
> 
> Highlights
> 
>   :heavy_check_mark: **media-session is now moved into a separate module to speed up its deprecation in favour of WirePlumber.**
> - There is now an LD_PRELOAD v4l2 emulation library to run some existing v4l2 applications on top of PipeWire.
> - Filter-chains should now flush out remaining samples when paused. There is now also the option to let a filter-chain drain so that long filters such as reverbs can fade out properly.
> - Stability and compatibility improvements in JACK apps.
> - Better Bluetooth compatibility with more devices.
> - libcamera plugin improvements.
> - Many bugfixes and improvements all over the map.
