### ISSUE TITLE
Is an update to 0.3.71 possible?

### ISSUE THREAD

**Issue by user3354** [pipewire-debian/pipewire-debian#91]
Pipewire is great and this PPA for us Debian based LTS users is very appreciated. Is it possible to update this PPA to Pipewire 0.3.71?

Thanks again for this PPA, is there a donation/coffee button? :-)

**Comment by user3354** [comment]
Nobody? Is there another PPA which I don't know about? Is everybody using non LTS distributions?

**Comment by dreamcat4** [comment]
Hi @user3354 ! In terms of LTS distros...

I am on 23.04 now here which is not LTS. and my pipewire version is still at `0.3.68` for me (for the time being, until it gets incremented), so it does not seem to be related to LTS / non-LTS thing.

It seems the IS ahead some TESTING repo... but as it clearly states on the PPA description - that is not meant for public to use. It may not be a good idea.

https://launchpad.net/~pipewire-debian/+archive/ubuntu/testing?field.series_filter=lunar

It is unclear reason(s) why not incremented yet. However @souravdas142 status is marked as **BUSY** right now. So that might be such reason. Or there could be some other technical reason(s). If you are less patient to wait longer he did put up some instructions on the wiki how to build locally some debs. Just have not tried myself yet... since it is a bit complex for most of us. HIH

**Comment by user3354** [comment]
Thanks for your reply, I even installed the latest Ubuntu Studio hoping for an actual version with no success. Checking your link revealed that the last build was three days ago, so there is hope, I guess. Thanks again.

**Comment by souravdas142** [comment]
Hi All,

@user3354  Yes, 0.3.71 is enabled. Enjoy.
@dreamcat4  Sorry  there is too much delay happened. Yeah now a days I am full busy.

Please feel free to report if there is some issue.

**Comment by dreamcat4** [comment]
no problem my friend! was happy to wait. we are all grateful for these updates / repos

**Comment by Pharmasolin** [comment]
@souravdas142 consider registering some platform where you can accept donation for your work, I think your work worth tips from a community who rely on your ppa.

**Comment by user3354** [comment]
Thanks a lot!  I can confirm it works with Linux Mint 21.1. Appreciate your work.

**Comment by VladimirMrzv** [comment]
Something wrong with ppa or my system. I see new version files on ppa site, but after apt update still no new version.
I am on 22.04 jammy, somebody can help me, other deb packages was updated successfully.

**Comment by lriesebos** [comment]
hey @souravdas142 , I understand you have been busy so definitely don't want to poke you too much. though there is a known bluetooth issue in 0.3.71 that has been resolved in 0.3.72/0.3.73. see https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3248.

**Comment by souravdas142** [comment]
> @souravdas142 consider registering some platform where you can accept donation for your work, I think your work worth tips from a community who rely on your ppa.

HI @Pharmasolin @user3354 

Thanks for you support. now the project accept donation.

**Comment by Pharmasolin** [comment]
@souravdas142 just added my contribution via paypal. But when I tried using my card directly on a website I couldn't do it, got this error. Check if you can fix this, so more people can show their gratitude for your work!
![image](https://github.com/pipewire-debian/pipewire-debian/assets/13041082/54fbe0d1-c971-4387-9d91-68469fbf95f8)

**Comment by souravdas142** [comment]
@Pharmasolin things are now working.

**Comment by souravdas142** [comment]
PipeWire updated to 0.3.82.

So closing.
